name: Trigger Test Automation Repo

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test repo workflow
        uses: peter-evans/repository-dispatch@v3.0.0 #This is a custom trigger
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: MahmoudFawzyAOE2/mft1998-portfolio-TestAutomation
          event-type: run-tests
